/** Declaration file generated by dts-gen */

declare module 'ot-json0' {
  const ot_json0: {
    type: {
      append: any;
      apply: (json: any, op: any[]) => any;
      canOpAffectPath: any;
      checkList: any;
      checkObj: any;
      checkValidOp: any;
      commonLengthForOps: any;
      compose: (op1: any[], op2: any[]) => any[];
      create: any;
      incrementalApply: any;
      invert: any;
      invertComponent: any;
      name: string;
      normalize: (op: any[]) => any[];
      pathMatches: any;
      registerSubtype: any;
      shatter: any;
      transform: (op: any[], otherOp: any[], side: 'left'|'right') => any[];
      transformComponent: any;
      transformX: any;
      uri: string;
    };
  };
  export = ot_json0;
}


