/** Declaration file generated by dts-gen */

declare module 'ot-text' {
  const ot_text: {
    type: {
      api: any;
      apply: (str: string, op: any[]) => string;
      compose: (op1: any[], op2: any[]) => any[];
      create: (initial: string) => string;
      name: string;
      normalize: (op: any[]) => any[];
      selectionEq: any;
      transform: (op: any[], otherOp: any[], side: 'left'|'right') => any[];
      transformSelection: any;
      uri: string;
    };
  };
  export = ot_text;
}
