/** Declaration file generated by dts-gen */

declare module 'text-diff-binding' {
  
  class text_diff_binding {
    element: Element;
    constructor(element: Element);

    onInput(): void;

    onInsert(index: number, length: number): void;

    onRemove(index: number, length: number): void;

    update(): void;

  }

  export = text_diff_binding;
}
