/** Declaration file generated by dts-gen */

import grpc from 'grpc';
export {grpc};

export * from './gen/base_grpc_pb';
export * from './gen/base_pb';
export * from './gen/text_pb';
// json_pb is not exported since it may clash with text_pb
